/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./src/components/animation.vue')['default']
    Check: typeof import('./src/components/check.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Lighting: typeof import('./src/components/lighting.vue')['default']
    Material: typeof import('./src/components/material.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scripts: typeof import('./src/components/Scripts.vue')['default']
    Sequence: typeof import('./src/components/Sequence.vue')['default']
    SideNavigation: typeof import('./src/components/SideNavigation.vue')['default']
    Utl: typeof import('./src/components/Utl.vue')['default']
  }
}
